before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/yt2rss.go 
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -s -w -X github.com/Fabian-G/yt2rss/cmd.version={{.Version}} -X github.com/Fabian-G/yt2rss/cmd.commit={{.Commit}} -X github.com/Fabian-G/yt2rss/cmd.date={{.Date}} -X github.com/Fabian-G/yt2rss/cmd.builtBy=goreleaser

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
announce:
  mastodon:
    enabled: true
    server: https://ohai.social
